---
- name: Sincronizar Azure com Jira Assets CMDB
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Incluir variáveis do role
      ansible.builtin.include_vars:
        file: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/../roles/integration_assets_azure/vars/main.yml"
        - "{{ playbook_dir }}/../roles/integration_assets_azure/vars/modelo_servidor_map_azure.yml"

  # pre_tasks:
  #   - name: Verificar token_aap
  #     ansible.builtin.assert:
  #       that:
  #         - token_aap is defined
  #         - token_aap | length > 0
  #       fail_msg: "Defina token_aap via extra-vars"

  #   - name: Verificar credenciais Jira
  #     ansible.builtin.assert:
  #       that:
  #         - lookup('env', 'JIRA_USER') | length > 0
  #         - lookup('env', 'JIRA_PASSWORD') | length > 0
  #       fail_msg: "Defina JIRA_USER e JIRA_PASSWORD no ambiente"

  roles:
    - role: integration_assets_azure
      vars:
        modelo_servidor_map: "{{ modelo_servidor_map }}"
